% ---------------------------------------------- 
% CREATE GAME INTERFACE
% ---------------------------------------------- 
function fig = create_ui

window = figure('Name', 'Sudoku',...
                'NumberTitle', 'off', ...
                'Units', 'pixels', ...
                'MenuBar', 'none', ...
                'ToolBar', 'none',...
                'Position',[400,150,650,485],...
                'Visible', 'on');
                         
game_help_panel = uipanel(window, ... 
                'Title','Having troubles?', ...
                'FontSize',12,...
                'BackgroundColor','white',...
                'Units', 'pixels', ...
                'Position',[430 310 200 140]);
            
gameData.btn_solve = uicontrol(game_help_panel, ...
                  'Style', 'pushbutton', ...
                  'String', 'Solve Puzzle', ...
                  'Callback', 'game_callback(''action_solve'', get(gcbf, ''UserData''));', ...
                  'Position', [20 70 150 50]);
                             
game_control_panel = uipanel(window, ...
                             'Title', 'Game Menu', ...
                             'FontSize', 12, ...
                             'BackgroundColor', 'white', ...
                             'Units', 'pixels', ... 
                             'Position', [430 90 200 210]);
                         
gameData.btn_generate = uicontrol(game_control_panel, ...
            'Style', 'pushbutton', ...
            'String', 'Generate New', ...
            'Callback', 'game_callback(''action_gen'', get(gcbf, ''UserData''));', ...
            'Position', [20 140 150 50]);
        
gameData.btn_load = uicontrol(game_control_panel, ...
            'Style', 'pushbutton', ...
            'String', 'Load Game File', ...
            'Callback', 'game_callback(''action_load'', get(gcbf, ''UserData''));', ...
            'Position', [20 85 150 50]);
    
gameData.btn_save = uicontrol(game_control_panel, ...
            'Style', 'pushbutton', ...
            'String', 'Save Game to File', ...
            'Callback', 'game_callback(''action_save'', get(gcbf, ''UserData''));', ...
            'Position', [20 30 150 50]);
              

%setup axes for game board
gameData.axes = axes(window, ...
    'Units', 'points', ...
    'Position', [40, 90, 360, 360], ...
    'XLim', [0 9], ...
    'YLim', [0 9], ...
    'Visible', 'off');

%setup board grid
for ind1 = 1:9
    for ind2 = 1:9
        rectangle('Position', [ind2-1, ind1-1, 1, 1]);
        if (any(ind2==[1 4 7]) && any(ind1==[1 4 7]))
           rectangle('Position', [ind2-1, ind1-1, 3, 3], 'LineWidth', 3); 
        end
    end
end

ui_state('init', gameData); %change ui state (sets save and solve button to unclickable)
set(window, 'UserData', gameData); %set game params
fig = window;
end